
state_space:
  x_lower: -3.0
  x_upper: 3.0
  y_lower: -3.0
  y_upper: 3.0
  turning_radius: 10.0

planner_ros:
  nav_msgs_path_topic: ompl_rs_planner_ros/nav_msgs_path
  planning_service_name: ompl_rs_planner_ros/planning_service
  path_msg_topic: ompl_rs_planner_ros/nav_msgs_path
  # path_frame: map
  path_frame: odom
  nav_msg_path_spatial_resolution: 1.5

planner:
  path_spatial_resolution: 1.5
  ompl_planner: RRTstar # see ompl_planner_creators.hpp for list of available planners
  max_planning_time: 60

ompl_planners:
  rrt_star:
    planner_range: 1.5
  rrt_sharp:
    planner_range: 15.0
